source "https://rubygems.org"

gem "jekyll", "4.3.3"
gem "json", "2.7.2"

group :jekyll_plugins do
  gem "jekyll-bookshop", "3.9.0"
  gem 'jekyll-tagging', "1.1.0"
  gem "jekyll-sitemap", "1.4.0"
end
